// Prisma CLI configuration (generated by `prisma init`, then adapted).
//
// Prisma's own dotenv loading only reads a plain `.env` file by default.
// This repository's documented local-environment convention is `.env.local`
// (docs/HERITAGE_V3_ENVIRONMENT_CONFIGURATION.md Section 7.2; gitignored,
// never committed), matching what Next.js itself reads. Loading it
// explicitly here means a developer maintains exactly one local secrets
// file for both the Next.js app and the Prisma CLI. In staging/production,
// `.env.local` will not exist and DATABASE_URL is already present in
// process.env (injected by the deployment target), so this call is a no-op
// there — dotenv never overwrites an already-set variable.
import { config } from 'dotenv';
import { defineConfig } from 'prisma/config';

config({ path: '.env.local' });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'tsx prisma/seed.ts',
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
